#!/bin/bash
set -o vi
set -f
server=$1
channel=global
function layout () {
	screen -S $server -X only
	screen -S $server -X select 0
	screen -S $server -X split
	screen -S $server -X focus
	screen -S $server -X select 1
	screen -S $server -X split
	screen -S $server -X focus
	screen -S $server -X select 2
	screen -S $server -X resize 1
}
layout

history -r ~/.mc_history
if [ -f ~/.bukkit ]; then
	. ~/.bukkit
fi

bukkit="sudo -u $server /home/$server/bin/bukkit"

function prompt () {
	if [ "$channel" = "global" ]; then
		prompt=$nick
	else
		prompt="${nick}(${channel})"
	fi
	read -r -e -p "$(printf "\001\033[33m\002[$server]\001\033[31m\002$prompt\001\033[m\002")> " first parameters
	
	if [ -z "$first" ]; then return; fi
	
	if [ "$first" = "/close" ]; then
		screen -S $server -X quit
		exit 0
	elif [ -n "$parameters" ]; then
		history -s "$first $parameters"
	else
		history -s "$first"
	fi
	
	history -w ~/.mc_history
	cmd=''
	emote=$(echo $first | sed -e 's/^!//')
	prefix=${first:0:1}
	command=$(echo $first | sed -e 's/^\///')
	
	if [ "$prefix" = "!" ] && [ -n "$emote" ]; then
		$bukkit command "puppet $nick $channel /$emote $parameters"
		return
	fi

	if [ $prefix != "/" ]; then
		$bukkit command "puppet $nick $channel $first $parameters"
		return
	fi
	
	case $command in
		1)
			if [ -z "$parameters" ]; then
				channel=global
			else
				$bukkit command "puppet $nick global $parameters"
			fi
			;;
		2)
			if [ -z "$parameters" ]; then
				channel=dev
			else
				$bukkit command "puppet $nick dev $parameters"
			fi
			;;
		3)
			if [ -z "$parameters" ]; then
				channel=staff
			else
				$bukkit command "puppet $nick staff $parameters"
			fi
			;;
		4)
			if [ -z "$parameters" ]; then
				channel=unsafe
			else
				$bukkit command "puppet $nick unsafe $parameters"
			fi
			;;
		f5)
			layout
			;;
		nick)
			nick=$parameters
			;;
		channel)
			channel=$parameters
			;;
		start)
			$bukkit start
			;;
		restart)
			$bukkit restart 0
			;;
		bukkit)
			parameters=$(echo $parameters | sed -e "s/'/'\"'\"'/g" -e 's/%/%%/')
			$bukkit $parameters
			;;
		*)
			$bukkit command "$command $parameters"
	esac
}

while true; do prompt; done
