#!/bin/bash

if [ -z "$2" ]; then
	echo "Usage: $0 servername [combine|split|standalone]"
	exit 1
fi

if [ -z "$3" ]; then
	while true; do
		$0 $1 $2 run
		if [ $? -gt 0 ]; then
			exit 1
		fi
	done
fi

set -o vi
set -f
server=$1
user=$(whoami)
layout=$2
if [ "$layout" != "standalone" ]; then
	session="${server}-${layout}-${user}"
fi
channel=global
if [ ! -z "$session" ]; then
	tmux-layout-$layout "$session" "$server"
fi

history -r ~/.mc_history
if [ -f ~/.bukkit ]; then
	. ~/.bukkit
fi

bukkit="sudo -u $server /home/$server/bin/bukkit"

function prompt () {
	if [ "$channel" = "global" ]; then
		prompt=$nick
	else
		prompt="${nick}(${channel})"
	fi
	read -r -e -p "$(printf "\001\033[33m\002[$server]\001\033[31m\002$prompt\001\033[m\002")> " first parameters
	
	if [ -z "$first" ]; then return; fi
	
	if [ "$first" = "/close" ]; then
		if [ -z "$session" ]; then
			exit 0
		fi
		tmux kill-session -t $session
		exit 1
	elif [ -n "$parameters" ]; then
		history -s "$first $parameters"
	else
		history -s "$first"
	fi
	
	history -w ~/.mc_history
	cmd=''
	emote=$(echo $first | sed -e 's/^!//')
	prefix=${first:0:1}
	command=$(echo $first | sed -e 's/^\///')
	
	if [ "$prefix" = "!" ] && [ -n "$emote" ]; then
		$bukkit command "puppet $nick $channel /$emote $parameters"
		return
	fi

	if [ $prefix != "/" ]; then
		$bukkit command "puppet $nick $channel $first $parameters"
		return
	fi
	
	case $command in
		1)
			if [ -z "$parameters" ]; then
				channel=global
			else
				$bukkit command "puppet $nick global $parameters"
			fi
			;;
		2)
			if [ -z "$parameters" ]; then
				channel=dev
			else
				$bukkit command "puppet $nick dev $parameters"
			fi
			;;
		3)
			if [ -z "$parameters" ]; then
				channel=staff
			else
				$bukkit command "puppet $nick staff $parameters"
			fi
			;;
		4)
			if [ -z "$parameters" ]; then
				channel=Unsafe
			else
				$bukkit command "puppet $nick Unsafe $parameters"
			fi
			;;
		f5)
			if [ -z "$session" ]; then
				echo "No tmux session, restarting bukkit CLI"
				exit 0
			fi
			tmux-layout-$layout "$session" "$server"
			exit 0
			;;
		close)
			exit 1
			;;
		nick)
			nick=$parameters
			echo "nick=${nick}" > ~/.bukkit
			echo "channel=${channel}" >> ~/.bukkit
			;;
		channel)
			channel=$parameters
			echo "nick=${nick}" > ~/.bukkit
			echo "channel=${channel}" >> ~/.bukkit
			;;
		start)
			$bukkit start
			;;
		restart)
			$bukkit restart 0
			;;
		bukkit)
			parameters=$(echo $parameters | sed -e "s/'/'\"'\"'/g" -e 's/%/%%/')
			$bukkit $parameters
			;;
		*)
			$bukkit command "$command $parameters"
	esac
}

while true; do prompt; done
