#!/bin/bash
server=$1
layout=$2
user=$(whoami)
session="${server}-${layout}-${user}"

tmux-layout-$layout "$session" "$server"
(sleep 2; tmux-layout-$layout "$session" "$server")&
tmux attach -t "$session"

echo 再び戻ってくる
